Project: MediaWiki
awesome-global-contributions/awesome-global-contributions pull request #35
Opened 2019-09-12 01:32 UTC by Fandekasp

PR 6/15 for #29

2019-09-12 16:25 UTC, OscarAblinger requested changes

2019-09-12 16:25 UTC, OscarAblinger commented on src/mediawiki.yaml
> +  - LESS
I assume `Lua` and `LESS` were meant for `programmingLanguages` not `frameworksUsed`? ^^

2019-09-13 00:06 UTC, AdrienLemaire commented on src/mediawiki.yaml
> +  - LESS
hmm... this warrants a discussion. Lua is only using in templates, and LESS is a CSS framework, so I wouldn't put them in the same category as other programming languages.
I'll just remove them for now :)

2019-09-13 11:03 UTC, AblingerOscar commented on src/mediawiki.yaml
> +  - LESS
I don't know enough about Lua to say much about it. I just looked it up and its website described it as a programming language 🤷‍♂ If you think it's more of a framework then leave it in there as that.

LESS, however, I'd definitely not define as a framework. In the end it only generates a file that is included into the HTML later on. It doesn't provide any generic functionality that is extended by its users.

2019-09-27 12:08 UTC, AblingerOscar commented
I think we should add Lua & Less somewhere (either frameworks or programming languages, since people might want to look for it 🤔

2019-09-30 13:45 UTC, OscarAblinger approved these changes

2019-10-01 00:35 UTC, merged